### PR TITLE
Sync repositories for manifests plan

### LINKED ISSUE #70: Fail if no helm config dir presents
Helmwave fails if no local helm config dir presents. Probably `helm init --client-only` would fix this, but it is no longer present in helm.

Also there is no log about it:
```
time="2021-03-08T06:52:05Z" level=info msg="📄 Render file" from=../fixtures/helmwave.yml.tpl to=helmwave.yml
time="2021-03-08T06:52:05Z" level=info msg="🛠 Yml -> 🛥 releases" releases="[nginx@test-nginx]"
time="2021-03-08T06:52:05Z" level=info msg="🛥 Sync releases"
time="2021-03-08T06:52:05Z" level=info msg="🛥 nginx@test-nginx"
time="2021-03-08T06:52:05Z" level=error msg="❌ failed to download \"bitnami/nginx\" (hint: running `helm repo update` may help)"
time="2021-03-08T06:52:05Z" level=info msg="Success 0 / 1"
time="2021-03-08T06:52:05Z" level=error msg="\"nginx\" was not deployed to \"test-nginx\""
```

### PR DESCRIPTION
**Pull request by r3nic1e**
Fixes #70

### CODE REVIEW

File: pkg/repo/helm.go [hunk 1]
```diff
@@ -25,6 +25,19 @@ func Write(repofile string, o *repo.Entry, helm *helm.EnvSettings) error {
 		return err
 	}
 
+	if _, err := os.Stat(repofile); os.IsNotExist(err) {
+		f, err := os.Create(repofile)
+		if err != nil {
+			return err
+		}
+		err = f.Close()
```
Comment (zhilyaev) [inline pkg/repo/helm.go:33]: `defer` is prefer

Comment (r3nic1e) [reply pkg/repo/helm.go:33]: you can't catch errors and return them via deferred functions

**Comment by r3nic1e** [comment]
@zhilyaev RTM
